using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using MvcMusicStore.Models;
using MvcMusicStore.ViewModels;

namespace MvcMusicStore.Utility
{
    // Fake MusicStoreEntities that was generated by Entity Framework
    public class MusicStoreEntities
    {
        public IList<Album> Albums { get { throw new NotImplementedException(); } }
        public IList<Genre> Genres { get { throw new NotImplementedException(); } }
        public IList<Artist> Artists { get { throw new NotImplementedException(); } }
        public IList<Cart> Carts { get { throw new NotImplementedException(); } }
        public IList<Order> Orders { get { throw new NotImplementedException(); } }
        public IList<OrderDetail> OrderDetails { get { throw new NotImplementedException(); } }
    }
}
